In [1]:
import pandas as pd
import numpy as np

In [2]:
arr=np.array([2,4,2,7,8])
arr

array([2, 4, 2, 7, 8])

In [3]:
arr.ndim

1

In [4]:
arr.shape

(5,)

In [5]:
arr.size

5

In [15]:
arr1=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
print(arr1.ndim, arr1.size, arr1.shape)

2 12 (4, 3)


In [17]:
arr2=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [18]:
print(arr2.ndim,arr2.size, arr2.shape)

3 18 (2, 3, 3)


In [19]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
arr1.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [21]:
arr1.reshape(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
arr1.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [29]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [34]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
arr1.max()

np.int64(11)

In [38]:
arr1.min()

np.int64(0)

In [40]:
arr1.sum()

np.int64(66)

In [41]:
arr1.sum(axis=0)

array([18, 22, 26])

In [42]:
arr1.sum(axis=1)

array([ 3, 12, 21, 30])

In [43]:
arr1.argmax()

np.int64(11)