In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("spam.csv")

In [3]:
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
df["Output"]=df.Category.map({"spam":1,"ham":0})

In [7]:
df.head()

,Category,Message,Output
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [8]:
df.shape

(5572, 3)

In [9]:
df.Message[2]

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [10]:
x=df.Message
y=df.Output

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [12]:
x_train.shape

(4457,)

In [13]:
type(x_train)

pandas.core.series.Series

In [14]:
x_train

4       Nah I don't think he goes to usf, he lives aro...
3270                   Raviyog Peripherals bhayandar east
5267         Anything lar then ü not going home 4 dinner?
2949    Nope but i'll b going 2 sch on fri quite early...
4293                                                G.W.R
                              ...                        
808                     Boooo you always work. Just quit.
2050             How much is blackberry bold2 in nigeria.
939     Urgent! call 09061749602 from Landline. Your c...
3736                       It‘s £6 to get in, is that ok?
2933    Only 2% students solved this CAT question in '...
Name: Message, Length: 4457, dtype: object

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [16]:
x_train_cv=cv.fit_transform(x_train)

In [17]:
x_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59335 stored elements and shape (4457, 7751)>

In [18]:
cv.get_feature_names_out()[5000]

'optin'

In [19]:
cv.vocabulary_

{'nah': 4706,
 'don': 2425,
 'think': 6881,
 'he': 3394,
 'goes': 3195,
 'to': 6966,
 'usf': 7243,
 'lives': 4177,
 'around': 1077,
 'here': 3440,
 'though': 6899,
 'raviyog': 5615,
 'peripherals': 5191,
 'bhayandar': 1349,
 'east': 2535,
 'anything': 1006,
 'lar': 4038,
 'then': 6861,
 'not': 4852,
 'going': 3200,
 'home': 3501,
 'dinner': 2347,
 'nope': 4839,
 'but': 1587,
 'll': 4181,
 'sch': 5981,
 'on': 4961,
 'fri': 3022,
 'quite': 5567,
 'early': 2528,
 'lor': 4229,
 'cos': 2038,
 'mys': 4696,
 'sis': 6229,
 'got': 3228,
 'paper': 5101,
 'in': 3668,
 'da': 2165,
 'morn': 4608,
 'have': 3383,
 'secret': 6021,
 'admirer': 835,
 'who': 7510,
 'is': 3777,
 'looking': 4223,
 'make': 4348,
 'contact': 2005,
 'with': 7559,
 'find': 2879,
 'out': 5039,
 'they': 6874,
 'reveal': 5810,
 'thinks': 6885,
 'ur': 7222,
 'so': 6326,
 'special': 6408,
 'call': 1620,
 '09065171142': 225,
 'stopsms': 6538,
 '08718727870150ppm': 153,
 'shall': 6108,
 'get': 3145,
 'my': 4691,
 'pouch': 5375,
 'its

In [23]:
x_train_np=x_train_cv.toarray()

In [24]:
x_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 7751))

In [25]:
x_train_np.shape

(4457, 7751)

In [27]:
np.where(x_train_np[5]!=0)

(array([ 153,  225,  835, 1620, 2005, 2879, 3383, 3777, 4223, 4348, 4961,
        5039, 5810, 6021, 6326, 6408, 6538, 6874, 6885, 7222, 7510, 7559]),)

In [29]:
x_train[5]

"FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv"

In [30]:
y_train[5]

np.int64(1)

In [33]:
from sklearn.naive_bayes import MultinomialNB
MB=MultinomialNB()

In [35]:
model=MB.fit(x_train_np,y_train)
model

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [37]:
x_test_cv=cv.transform(x_test)

In [38]:
x_test_np=x_test_cv.toarray()

In [40]:
y_pred=model.predict(x_test_np)

In [42]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9865470852017937

In [43]:
eg=["FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv",
    "As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune"]

In [45]:
lasan=cv.transform(eg)

In [46]:
model.predict(lasan)

array([0, 0])